program: Run.py
method: grid
metric:
  name: validation_loss
  goal: minimize
parameters:
  patch_height:
    values: [1, 2, 3]
  patch_width:
    values: [100, 250]
  to_take_perc:
    value: 0.15
  mask_or_same_perc:
    value: 0.7
  d_model:
    value: 128
  epochs:
    distribution: constant
    value: 10
  n_encoding_layers:
    values: [2, 3]  
  n_heads:
    values: [2, 4]
  dim_ff_ratio:
    values: [2, 3]
  pos_enc_type:
    values: ["1d", "2d"]
  decoding_type:
    values: ["rev", "nar", "fcn"]
  distributed:
    value: False
  num_workers:
    value: 4
  warmup:
    value: 4000
  n_leads:
    value: 12
  window:
    value: 2500
  reduced: 
    value: True
  n_classes:
    value: 9
  batch_size:
    value: 4096
  patience:
    value: 10
  early_stopping:
    value: True
  embedding_type:
    values: ["linear", "conv"]