wandb_version: 1

group0:
  desc: null
  value:
  - NSR
group1:
  desc: null
  value:
  - AAR
  - AED
  - ARH
group2:
  desc: null
  value:
  - AMI
  - AMIs
  - AnMIs
  - AnMI
  - CHD
  - CMI
  - ERe
  - HTV
  - IIs
  - ISTD
  - LIs
  - MI
  - MIs
  - NSSTTA
  - OldMI
  - STC
  - STD
  - STE
  - STIAb
  - TAb
  - TInv
group3:
  desc: null
  value:
  - AB
  - AFAFL
  - ATach
  - BPAC
  - BTS
  - CAF
  - CCR
  - CVCL/CCVCL
  - CD
  - CR
  - PAF
  - PSVT
  - PWC
  - RAF
  - SAAWR
  - WAP
  - AF
  - AFL
  - PAC
  - SVPB
  - +ROT
  - -ROT
group4:
  desc: null
  value:
  - AVB
  - AVD
  - AVJR
  - CHB
  - CIAHB
  - DIB
  - IIAVB
  - IIAVBII
  - ILBBB
  - IR
  - JE
  - LPFB
  - MoI
  - SAB
  - SARR
  - SND
  - VEsR
  - BBB
  - Brady
  - CLBBB
  - CRBBB
  - IAVB
  - IRBBB
  - LAnFB
  - LBBB
  - LPR
  - RBBB
  - SB
group5:
  desc: null
  value:
  - AVNRT
  - AVRT
  - SPRI
  - SVB
  - SVT
  - VPEx
  - WPW
  - SA
  - STach
group6:
  desc: null
  value:
  - abQRS
  - AH
  - BRU
  - FQRS
  - HF
  - HVD
  - ICA
  - LAA
  - LAE
  - LAH
  - LVH
  - LVHV
  - LVS
  - PPW
  - RAAb
  - RAb
  - RAH
  - RAHV
  - RVH
  - SQT
  - TPW
  - UAb
  - VH
  - LAD
  - LQRSV
  - NSIVCB
  - PRWP
  - LQT
  - QAb
  - RAD
group7:
  desc: null
  value:
  - AP
  - VPP
  - PR
group8:
  desc: null
  value:
  - AIVR
  - AJR
  - FB
  - JPC
  - JTach
  - PVT
  - VBig
  - VEB
  - VEsB
  - VF
  - VFL
  - VPVC
  - VTach
  - VTrig
  - PVC
  - VPB
n_classes:
  desc: null
  value: 9
target_fs:
  desc: null
  value: 500
filter_bandwidth:
  desc: null
  value:
  - 0.05
  - 47
window:
  desc: null
  value: 5000
patch_height:
  desc: null
  value: 2
patch_width:
  desc: null
  value: 1000
mask_perc:
  desc: null
  value: 0.7
d_model:
  desc: null
  value: 128
n_leads:
  desc: null
  value: 12
epochs:
  desc: null
  value: 1
patience:
  desc: null
  value: 5
n_encoder_layers:
  desc: null
  value: 4
warmup:
  desc: null
  value: 4000
n_heads:
  desc: null
  value: 4
dim_ff:
  desc: null
  value: 512
hidden_dim:
  desc: null
  value: 128
batch_size:
  desc: null
  value: 1600
embedder_type:
  desc: null
  value: conv
pos_enc_type:
  desc: null
  value: 1d
decoding_type:
  desc: null
  value:
  - fcn
  - mirrored
  - nar
  - None
n_patches:
  desc: null
  value: 30
mask_token:
  desc: null
  value:
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
patch_size:
  desc: null
  value:
  - 2
  - 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686059395.363914
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.15.1
      8:
      - 5
