program: Run.py
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  patch_height:
    values: [1, 2, 3]
  patch_width:
    values: [100, 250]
  to_take_perc:
    value: 0.15
  mask_or_same_perc:
    value: 0.7
  d_model:
    values: [128, 256, 512]
  epochs:
    distribution: constant
    value: 10
  n_encoding_layers:
    values: [2, 3]  
  n_heads:
    values: [2, 4]
  dim_ff_ratio:
    values: [2, 3]
  pos_enc_type:
    values: ["1d", "2d"]
  learnable_pos_enc:
    values: [True, False]
  decoding_type:
    value: "rev"
  lr:
    distribution: uniform
    max: 0.001
    min: 0.0001
  beta1:
    distribution: uniform
    max: 0.95
    min: 0.9
  beta2:
    distribution: uniform
    max: 0.99
    min: 0.95
  distributed:
    value: False
  num_workers:
    value: 4
  warmup:
    value: 4000
  n_leads:
    value: 12
  window:
    value: 2500
  reduced: 
    value: True
  n_classes:
    value: 9
  batch_size:
    value: 4096
  patience:
    value: 8
  early_stopping:
    value: True
  embedding_type:
    values: ["linear", "conv"]