#!/bin/bash

hubert-ecg-finetune 3 /path/to/ribeiro_train.csv /path/to/ribeiro_val.csv 6 5 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=5000 --finetuning_layerdrop=0.0 --wandb_run_name=SMALL_random_ribeiro

hubert-ecg-finetune 3 /path/to/ningbo_train_0.csv /path/to/ningbo_val_0.csv 76 10 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_ningbo0
hubert-ecg-finetune 3 /path/to/ningbo_train_1.csv /path/to/ningbo_val_1.csv 76 10 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_ningbo1
hubert-ecg-finetune 3 /path/to/ningbo_train_2.csv /path/to/ningbo_val_2.csv 76 10 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_ningbo2
hubert-ecg-finetune 3 /path/to/ningbo_train_3.csv /path/to/ningbo_val_3.csv 76 10 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_ningbo3

hubert-ecg-finetune 3 /path/to/ptb_train_0.csv /path/to/ptb_train_0.csv 14 3 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb0
hubert-ecg-finetune 3 /path/to/ptb_train_1.csv /path/to/ptb_train_1.csv 14 3 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb1
hubert-ecg-finetune 3 /path/to/ptb_train_2.csv /path/to/ptb_train_2.csv 14 3 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb2
hubert-ecg-finetune 3 /path/to/ptb_train_3.csv /path/to/ptb_train_3.csv 14 3 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb3

hubert-ecg-finetune 3 /path/to/cpsc_train_0.csv /path/to/cpsc_val_0.csv 9 13 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_cpsc0
hubert-ecg-finetune 3 /path/to/cpsc_train_1.csv /path/to/cpsc_val_1.csv 9 13 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_cpsc1
hubert-ecg-finetune 3 /path/to/cpsc_train_2.csv /path/to/cpsc_val_2.csv 9 13 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_cpsc2
hubert-ecg-finetune 3 /path/to/cpsc_train_3.csv /path/to/cpsc_val_3.csv 9 13 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_cpsc3

hubert-ecg-finetune 3 /path/to/sph_supervised_processed_train.csv /path/to/sph_supervised_processed_val.csv 44 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=4 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_sph

hubert-ecg-finetune 3 /path/to/hefei_train.csv /path/to/hefei_val.csv 27 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_hefei3
hubert-ecg-finetune 3 /path/to/hefei_train_0.csv /path/to/hefei_val_0.csv 27 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_hefei0
hubert-ecg-finetune 3 /path/to/hefei_train_1.csv /path/to/hefei_val_1.csv 27 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_hefei1
hubert-ecg-finetune 3 /path/to/hefei_train_2.csv /path/to/hefei_val_2.csv 27 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_hefei2

hubert-ecg-finetune 3 /path/to/ptb_all_train.csv /path/to/ptb_all_val.csv 71 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=4 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb_all

hubert-ecg-finetune 3 /path/to/ptb_form_train.csv /path/to/ptb_form_val.csv 19 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=4 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb_form

hubert-ecg-finetune 3 /path/to/ptb_rhythm_train.csv /path/to/ptb_rhythm_val.csv 12 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=4 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb_rhythm

hubert-ecg-finetune 3 /path/to/ptb_diag_train.csv /path/to/ptb_diag_val.csv 44 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=4 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb_diag

hubert-ecg-finetune 3 /path/to/ptb_diag_subclass_train.csv /path/to/ptb_diag_subclass_val.csv 23 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=4 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb_diag_subclass

hubert-ecg-finetune 3 /path/to/ptb_diag_superclass_train.csv /path/to/ptb_diag_superclass_val.csv 5 8 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=4 --use_loss_weights --random_init --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_ptb_diag_superclass

hubert-ecg-finetune 3 /path/to/georgia_train_0.csv /path/to/georgia_val_0.csv 62 15 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_georgia0
hubert-ecg-finetune 3 /path/to/georgia_train_1.csv /path/to/georgia_val_1.csv 62 15 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_georgia1
hubert-ecg-finetune 3 /path/to/georgia_train_2.csv /path/to/georgia_val_2.csv 62 15 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_georgia2
hubert-ecg-finetune 3 /path/to/georgia_train_3.csv /path/to/georgia_val_3.csv 62 15 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=SMALL_random_georgia3

hubert-ecg-finetune 3 /path/to/chapman_train0.csv /path/to/chapman_val0.csv 52 20 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_chapman0
hubert-ecg-finetune 3 /path/to/chapman_train1.csv /path/to/chapman_val1.csv 52 20 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_chapman1
hubert-ecg-finetune 3 /path/to/chapman_train2.csv /path/to/chapman_val2.csv 52 20 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_chapman2
hubert-ecg-finetune 3 /path/to/chapman_train3.csv /path/to/chapman_val3.csv 52 20 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=small --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_chapman3

hubert-ecg-finetune 3 /path/to/samitrop_train0.csv /path/to/samitrop_train0.csv 2 20 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=SMALL_random_samitrop0 --task=multi_class --random_init --largeness=small
hubert-ecg-finetune 3 /path/to/samitrop_train1.csv /path/to/samitrop_train1.csv 2 20 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=SMALL_random_samitrop1 --task=multi_class --random_init --largeness=small
hubert-ecg-finetune 3 /path/to/samitrop_train2.csv /path/to/samitrop_train2.csv 2 20 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=SMALL_random_samitrop2 --task=multi_class --random_init --largeness=small
hubert-ecg-finetune 3 /path/to/samitrop_train3.csv /path/to/samitrop_train3.csv 2 20 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=SMALL_random_samitrop3 --task=multi_class --random_init --largeness=small

hubert-ecg-finetune 3 /path/to/cpsc_extra_train_0.csv /path/to/cpsc_extra_train_0.csv 52 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_cpsc_extra0 --random_init --largeness=small
hubert-ecg-finetune 3 /path/to/cpsc_extra_train_1.csv /path/to/cpsc_extra_train_1.csv 52 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_cpsc_extra1 --random_init --largeness=small
hubert-ecg-finetune 3 /path/to/cpsc_extra_train_2.csv /path/to/cpsc_extra_train_2.csv 52 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_cpsc_extra2 --random_init --largeness=small
hubert-ecg-finetune 3 /path/to/cpsc_extra_train_3.csv /path/to/cpsc_extra_train_3.csv 52 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=SMALL_random_cpsc_extra3 --random_init --largeness=small

hubert-ecg-finetune 3 /path/to/cardiolearning_train_0.csv /path/to/cardiolearning_val_0.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=small --wandb_run_name=cardiolearning_random0_small
hubert-ecg-finetune 3 /path/to/cardiolearning_train_1.csv /path/to/cardiolearning_val_1.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=small --wandb_run_name=cardiolearning_random1_small
hubert-ecg-finetune 3 /path/to/cardiolearning_train_2.csv /path/to/cardiolearning_val_2.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=small --wandb_run_name=cardiolearning_random2_small
hubert-ecg-finetune 3 /path/to/cardiolearning_train_3.csv /path/to/cardiolearning_val_3.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=small --wandb_run_name=cardiolearning_random3_small


# base model size


hubert-ecg-finetune 3 /path/to/ribeiro_train.csv /path/to/ribeiro_val.csv 6 5 64 auroc --training_steps=70000 --downsampling_factor=5 --largeness=base --label_start_index=3 --use_loss_weights --random_init --dynamic_reg --val_interval=5000 --finetuning_layerdrop=0.0 --wandb_run_name=BASE_random_ribeiro

hubert-ecg-finetune 2 /path/to/ningbo_train_0.csv /path/to/ningbo_val_0.csv 76 10 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ningbo0
hubert-ecg-finetune 2 /path/to/ningbo_train_1.csv /path/to/ningbo_val_1.csv 76 10 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ningbo1
hubert-ecg-finetune 2 /path/to/ningbo_train_2.csv /path/to/ningbo_val_2.csv 76 10 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ningbo2
hubert-ecg-finetune 2 /path/to/ningbo_train_3.csv /path/to/ningbo_val_3.csv 76 10 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ningbo3

hubert-ecg-finetune 2 /path/to/ptb_train_0.csv /path/to/ptb_train_0.csv 14 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_ptb0
hubert-ecg-finetune 2 /path/to/ptb_train_1.csv /path/to/ptb_train_1.csv 14 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_ptb1
hubert-ecg-finetune 2 /path/to/ptb_train_2.csv /path/to/ptb_train_2.csv 14 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_ptb2
hubert-ecg-finetune 2 /path/to/ptb_train_3.csv /path/to/ptb_train_3.csv 14 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_ptb3

hubert-ecg-finetune 2 /path/to/cpsc_train_0.csv /path/to/cpsc_val_0.csv 9 13 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.2 --random_crop --wandb_run_name=BASE_random_cpsc0
hubert-ecg-finetune 2 /path/to/cpsc_train_1.csv /path/to/cpsc_val_1.csv 9 13 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.2 --random_crop --wandb_run_name=BASE_random_cpsc1
hubert-ecg-finetune 2 /path/to/cpsc_train_2.csv /path/to/cpsc_val_2.csv 9 13 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.2 --random_crop --wandb_run_name=BASE_random_cpsc2
hubert-ecg-finetune 2 /path/to/cpsc_train_3.csv /path/to/cpsc_val_3.csv 9 13 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.2 --random_crop --wandb_run_name=BASE_random_cpsc3

hubert-ecg-finetune 2 /path/to/sph_supervised_processed_train.csv /path/to/sph_supervised_processed_val.csv 44 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_sph

hubert-ecg-finetune 2 /path/to/hefei_train.csv /path/to/hefei_val.csv 27 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_hefei3
hubert-ecg-finetune 2 /path/to/hefei_train_0.csv /path/to/hefei_val_0.csv 27 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_hefei0
hubert-ecg-finetune 2 /path/to/hefei_train_1.csv /path/to/hefei_val_1.csv 27 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_hefei1
hubert-ecg-finetune 2 /path/to/hefei_train_2.csv /path/to/hefei_val_2.csv 27 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_hefei2

hubert-ecg-finetune 2 /path/to/ptb_all_train.csv /path/to/ptb_all_val.csv 71 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ptb_all

hubert-ecg-finetune 2 /path/to/ptb_form_train.csv /path/to/ptb_form_val.csv 19 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ptb_form

hubert-ecg-finetune 2 /path/to/ptb_rhythm_train.csv /path/to/ptb_rhythm_val.csv 12 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ptb_rhythm

hubert-ecg-finetune 2 /path/to/ptb_diag_train.csv /path/to/ptb_diag_val.csv 44 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ptb_diag

hubert-ecg-finetune 2 /path/to/ptb_diag_subclass_train.csv /path/to/ptb_diag_subclass_val.csv 23 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ptb_diag_subclass

hubert-ecg-finetune 2 /path/to/ptb_diag_superclass_train.csv /path/to/ptb_diag_superclass_val.csv 5 8 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=BASE_random_ptb_diag_superclass

hubert-ecg-finetune 2 /path/to/samitrop_train0.csv /path/to/samitrop_train0.csv 2 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=BASE_random_samitrop0 --task=multi_class
hubert-ecg-finetune 2 /path/to/samitrop_train1.csv /path/to/samitrop_train1.csv 2 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=BASE_random_samitrop1 --task=multi_class
hubert-ecg-finetune 2 /path/to/samitrop_train2.csv /path/to/samitrop_train2.csv 2 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=BASE_random_samitrop2 --task=multi_class
hubert-ecg-finetune 2 /path/to/samitrop_train3.csv /path/to/samitrop_train3.csv 2 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=BASE_random_samitrop3 --task=multi_class

hubert-ecg-finetune 3 /path/to/cpsc_extra_train_0.csv /path/to/cpsc_extra_train_0.csv 52 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_cpsc_extra0
hubert-ecg-finetune 3 /path/to/cpsc_extra_train_1.csv /path/to/cpsc_extra_train_1.csv 52 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_cpsc_extra1
hubert-ecg-finetune 3 /path/to/cpsc_extra_train_2.csv /path/to/cpsc_extra_train_2.csv 52 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_cpsc_extra2
hubert-ecg-finetune 3 /path/to/cpsc_extra_train_3.csv /path/to/cpsc_extra_train_3.csv 52 3 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_cpsc_extra3

hubert-ecg-finetune 3 /path/to/georgia_train_0.csv /path/to/georgia_val_0.csv 62 15 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.2 --random_crop --wandb_run_name=BASE_random_georgia0
hubert-ecg-finetune 3 /path/to/georgia_train_1.csv /path/to/georgia_val_1.csv 62 15 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.2 --random_crop --wandb_run_name=BASE_random_georgia1
hubert-ecg-finetune 3 /path/to/georgia_train_2.csv /path/to/georgia_val_2.csv 62 15 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.2 --random_crop --wandb_run_name=BASE_random_georgia2
hubert-ecg-finetune 3 /path/to/georgia_train_3.csv /path/to/georgia_val_3.csv 62 15 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.2 --random_crop --wandb_run_name=BASE_random_georgia3

hubert-ecg-finetune 3 /path/to/chapman_train0.csv /path/to/chapman_val0.csv 52 15 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_chapman0
hubert-ecg-finetune 3 /path/to/chapman_train1.csv /path/to/chapman_val1.csv 52 15 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_chapman1
hubert-ecg-finetune 3 /path/to/chapman_train2.csv /path/to/chapman_val2.csv 52 15 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_chapman2
hubert-ecg-finetune 3 /path/to/chapman_train3.csv /path/to/chapman_val3.csv 52 15 64 auroc --largeness=base --dynamic_reg --random_init --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=BASE_random_chapman3

hubert-ecg-finetune 2 /path/to/cardiolearning_train_0.csv /path/to/cardiolearning_val_0.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=base --wandb_run_name=cardiolearning_random0_base
hubert-ecg-finetune 2 /path/to/cardiolearning_train_0.csv /path/to/cardiolearning_val_0.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=base --wandb_run_name=cardiolearning_random1_base
hubert-ecg-finetune 2 /path/to/cardiolearning_train_0.csv /path/to/cardiolearning_val_0.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=base --wandb_run_name=cardiolearning_random2_base
hubert-ecg-finetune 2 /path/to/cardiolearning_train_0.csv /path/to/cardiolearning_val_0.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=base --wandb_run_name=cardiolearning_random3_base

# large model size 

hubert-ecg-finetune 3 /path/to/ribeiro_train.csv /path/to/ribeiro_val.csv 6 5 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=5000 --finetuning_layerdrop=0.0 --wandb_run_name=LARGE_random_ribeiro

hubert-ecg-finetune 3 /path/to/ningbo_train_0.csv /path/to/ningbo_val_0.csv 76 10 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_ningbo0
hubert-ecg-finetune 3 /path/to/ningbo_train_1.csv /path/to/ningbo_val_1.csv 76 10 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_ningbo1
hubert-ecg-finetune 3 /path/to/ningbo_train_2.csv /path/to/ningbo_val_2.csv 76 10 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_ningbo2
hubert-ecg-finetune 3 /path/to/ningbo_train_3.csv /path/to/ningbo_val_3.csv 76 10 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_ningbo3

hubert-ecg-finetune 3 /path/to/ptb_train_0.csv /path/to/ptb_train_0.csv 14 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_ptb0
hubert-ecg-finetune 3 /path/to/ptb_train_1.csv /path/to/ptb_train_1.csv 14 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_ptb1
hubert-ecg-finetune 3 /path/to/ptb_train_2.csv /path/to/ptb_train_2.csv 14 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_ptb2
hubert-ecg-finetune 3 /path/to/ptb_train_3.csv /path/to/ptb_train_3.csv 14 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_ptb3

hubert-ecg-finetune 3 /path/to/cpsc_train_0.csv /path/to/cpsc_val_0.csv 9 13 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_cpsc0
hubert-ecg-finetune 3 /path/to/cpsc_train_1.csv /path/to/cpsc_val_1.csv 9 13 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_cpsc1
hubert-ecg-finetune 3 /path/to/cpsc_train_2.csv /path/to/cpsc_val_2.csv 9 13 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_cpsc2
hubert-ecg-finetune 3 /path/to/cpsc_train_3.csv /path/to/cpsc_val_3.csv 9 13 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_cpsc3

hubert-ecg-finetune 3 /path/to/sph_supervised_processed_train.csv /path/to/sph_supervised_processed_val.csv 44 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_sph

hubert-ecg-finetune 3 /path/to/hefei_train.csv /path/to/hefei_val.csv 27 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_hefei3
hubert-ecg-finetune 3 /path/to/hefei_train_0.csv /path/to/hefei_val_0.csv 27 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_hefei0
hubert-ecg-finetune 3 /path/to/hefei_train_1.csv /path/to/hefei_val_1.csv 27 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_hefei1
hubert-ecg-finetune 3 /path/to/hefei_train_2.csv /path/to/hefei_val_2.csv 27 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_hefei2

hubert-ecg-finetune 3 /path/to/ptb_all_train.csv /path/to/ptb_all_val.csv 71 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=LARGE_random_ptb_all


hubert-ecg-finetune 3 /path/to/ptb_form_train.csv /path/to/ptb_form_val.csv 19 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=LARGE_random_ptb_form

hubert-ecg-finetune 3 /path/to/ptb_rhythm_train.csv /path/to/ptb_rhythm_val.csv 12 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=LARGE_random_ptb_rhythm

hubert-ecg-finetune 3 /path/to/ptb_diag_train.csv /path/to/ptb_diag_val.csv 44 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=LARGE_random_ptb_diag

hubert-ecg-finetune 3 /path/to/ptb_diag_subclass_train.csv /path/to/ptb_diag_subclass_val.csv 23 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=LARGE_random_ptb_diag_subclass

hubert-ecg-finetune 3 /path/to/ptb_diag_superclass_train.csv /path/to/ptb_diag_superclass_val.csv 5 8 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=4 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=500 --finetuning_layerdrop=0.1 --random_crop --wandb_run_name=LARGE_random_ptb_diag_superclass

hubert-ecg-finetune 3 /path/to/samitrop_train0.csv /path/to/samitrop_train0.csv 2 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=LARGE_random_samitrop0 --task=multi_class
hubert-ecg-finetune 3 /path/to/samitrop_train1.csv /path/to/samitrop_train1.csv 2 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=LARGE_random_samitrop1 --task=multi_class
hubert-ecg-finetune 3 /path/to/samitrop_train2.csv /path/to/samitrop_train2.csv 2 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=LARGE_random_samitrop2 --task=multi_class
hubert-ecg-finetune 3 /path/to/samitrop_train3.csv /path/to/samitrop_train3.csv 2 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=6 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0. --random_crop --wandb_run_name=LARGE_random_samitrop3 --task=multi_class

hubert-ecg-finetune 3 /path/to/cpsc_extra_train_0.csv /path/to/cpsc_extra_train_0.csv 52 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_cpsc_extra0
hubert-ecg-finetune 3 /path/to/cpsc_extra_train_1.csv /path/to/cpsc_extra_train_1.csv 52 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_cpsc_extra1
hubert-ecg-finetune 3 /path/to/cpsc_extra_train_2.csv /path/to/cpsc_extra_train_2.csv 52 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_cpsc_extra2
hubert-ecg-finetune 3 /path/to/cpsc_extra_train_3.csv /path/to/cpsc_extra_train_3.csv 52 3 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_cpsc_extra3

hubert-ecg-finetune 3 /path/to/georgia_train_0.csv /path/to/georgia_val_0.csv 62 15 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_georgia0
hubert-ecg-finetune 3 /path/to/georgia_train_1.csv /path/to/georgia_val_1.csv 62 15 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_georgia1
hubert-ecg-finetune 3 /path/to/georgia_train_2.csv /path/to/georgia_val_2.csv 62 15 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_georgia2
hubert-ecg-finetune 3 /path/to/georgia_train_3.csv /path/to/georgia_val_3.csv 62 15 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_georgia3

hubert-ecg-finetune 3 /path/to/chapman_train0.csv /path/to/chapman_val0.csv 52 15 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_chapman0
hubert-ecg-finetune 3 /path/to/chapman_train1.csv /path/to/chapman_val1.csv 52 15 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_chapman1
hubert-ecg-finetune 3 /path/to/chapman_train2.csv /path/to/chapman_val2.csv 52 15 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_chapman2
hubert-ecg-finetune 3 /path/to/chapman_train3.csv /path/to/chapman_val3.csv 52 15 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --random_init --largeness=large --dynamic_reg --val_interval=50 --finetuning_layerdrop=0.0 --random_crop --wandb_run_name=LARGE_random_chapman3

hubert-ecg-finetune 3 /path/to/cardiolearning_train_0.csv /path/to/cardiolearning_val_0.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=large --wandb_run_name=cardiolearning_random0_large 
hubert-ecg-finetune 3 /path/to/cardiolearning_train_0.csv /path/to/cardiolearning_val_0.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=large --wandb_run_name=cardiolearning_random1_large 
hubert-ecg-finetune 3 /path/to/cardiolearning_train_0.csv /path/to/cardiolearning_val_0.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=large --wandb_run_name=cardiolearning_rando2_large 
hubert-ecg-finetune 3 /path/to/cardiolearning_train_0.csv /path/to/cardiolearning_val_0.csv 164 12 64 auroc --training_steps=70000 --downsampling_factor=5 --label_start_index=3 --use_loss_weights --val_interval=500 --finetuning_layerdrop=0.0 --random_crop --random_init --dynamic_reg --largeness=large --wandb_run_name=cardiolearning_random3_large 
